/*
 * Copyright (C) 2016 Thomas Kercheval
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package card_game_24.gui_dialogs;

import java.awt.Toolkit;

/**
 * The About form for this project.
 *
 * Project: 24 Card Game
 * Platform: jdk 1.8.0_14; NetBeans IDE 8.1; Windows 10
 * Course: CS 143 
 * Created on May 8, 2016, 4:06:51 PM 
 * Revised on May 31, 2016, 7:43:12 PM
 *
 * @author thomas.kercheval
 */
public class AboutForm extends javax.swing.JDialog {

    /**
     * Creates new form AboutForm. Sets modal, sets icon, and sets caret
     * position to start at beginning of the text box.
     */
    public AboutForm() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage("src/card_game_24/images/cards/king_of_hearts.png"));
        this.getRootPane().setDefaultButton(closeJButton);
        this.setModal(true);
        setLocationRelativeTo(null);
        this.aboutTextArea.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJPanel = new javax.swing.JPanel();
        logoJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        aboutJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutTextArea = new javax.swing.JTextArea();
        bottomPanel = new javax.swing.JPanel();
        copyrightJLabel = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        warningJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About 24 Card Game");
        setResizable(false);

        logoJLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        logoJLabel.setForeground(new java.awt.Color(51, 0, 0));
        logoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card_game_24/images/kinglogo-panel.png"))); // NOI18N

        titleJLabel.setFont(new java.awt.Font("AR JULIAN", 0, 24)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(51, 0, 0));
        titleJLabel.setText("24 Card Game Project");

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(logoJLabel)
                .addGap(18, 18, 18)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(titleJPanel, java.awt.BorderLayout.NORTH);

        aboutTextArea.setEditable(false);
        aboutTextArea.setColumns(20);
        aboutTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        aboutTextArea.setLineWrap(true);
        aboutTextArea.setRows(5);
        aboutTextArea.setText("## 24 Card Game\n\nA Java implementation of the card game \"24\", for my CS 143 class (Spr16, SCC).\n\n#### Project Objective:\n\nTo create a GUI in which users may create accounts and keep track of their\nscore as they play the card game \"24\".\n\nFour cards are dealt and the player must use four arithmetic operators (i.e.,\n\"+\", \"-\", \"\\*\", \"/\") to create an algebraic expression which evaluates to 24.\n\n#### Features:\n\n  - Redundant mathematical expressions are checked for and not counted as\n      new solutions (e.g., a + b - c, and, a - (c - b), are not counted\n      as two distinct answers).\n  - Infix expressions are evaluated using two Generic Stacks.\n  - Users may select, create, edit, and search for players.\n  - User may login as Guest Player and choose to not record their statistics.\n  - Players are stored in an XML database.\n  - User may shuffle cards if they cannot find more solutions to the current\n      hand.\n  - Player statistics are displayed on the right side of the screen.\n  - Player statistics may be printed.\n  - Entire GUI may be printed.\n  - High scores are recorded and kept.\n  - Total games played are recorded and kept.\n  - Player class inherits from Person class. (project requirement)\n  - DeckOfCards class creates entire deck of images at startup and doesn't\n      reload images every time the hand is shuffled.\n  - Custom icon is displayed on every form.\n  - Project Logo is displayed on every form.\n  - Full ToolTip provided.\n  - Project fully documented.\n  - Splash-Screen on startup.\n\n##### Contact:\n\n    Thomas Kercheval -> spacekattpoispin@gmail.com\n\n##### Notes:\n\n  - This project is backed up on GitHub.\n  - This project is licensed under GPL v3.0\n  - This project was developed on Windows 10.\n  - Moving around ones that are being multiplied/divided may give additional\n      points and are counted as distinct solutions.\n  - Next step would be to generate all solutions for a given hand, then\n      generate all possible hands drawn from the deck.\n  - Press Enter to close this window\n");
        aboutTextArea.setToolTipText("About this project");
        aboutTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(aboutTextArea);

        javax.swing.GroupLayout aboutJPanelLayout = new javax.swing.GroupLayout(aboutJPanel);
        aboutJPanel.setLayout(aboutJPanelLayout);
        aboutJPanelLayout.setHorizontalGroup(
            aboutJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutJPanelLayout.setVerticalGroup(
            aboutJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutJPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(aboutJPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.GridLayout(1, 0));

        copyrightJLabel.setText("Copyright 2016; Thomas Kercheval");
        copyrightJLabel.setToolTipText("It's my name :D");
        bottomPanel.add(copyrightJLabel);

        closeJButton.setMnemonic('c');
        closeJButton.setText("Close");
        closeJButton.setToolTipText("Close this about window");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(closeJButton);

        warningJLabel.setText("If: Steal Code -> Then: Suffer Curse");
        warningJLabel.setToolTipText("@see Death");
        bottomPanel.add(warningJLabel);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the About form and returns to main GUI.
     * @param evt The event which triggers this listener.
     */
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutJPanel;
    private javax.swing.JTextArea aboutTextArea;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel copyrightJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    private javax.swing.JLabel warningJLabel;
    // End of variables declaration//GEN-END:variables
}
